server {
    listen 80;
    listen [::]:80;
    server_name garypezza.com www.garypezza.com;

    root /opt/apps/garypezza-site;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
